# Generated by Django 3.1.1 on 2020-09-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0005_auto_20200912_1233'),
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('afterTransactionQuantity', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('transactionType', models.CharField(max_length=100, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
