# Generated by Django 3.1.1 on 2020-09-24 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 24, 10, 27, 12, 758661, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
