# Generated by Django 3.1.1 on 2020-10-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0005_auto_20201013_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/subcategory/'),
        ),
    ]
