# Generated by Django 3.1.2 on 2020-11-10 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201019_1052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0006_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.EmailField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
