# Generated by Django 3.1.5 on 2021-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_settings_appupdatemandetory'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='acceptOrder',
            field=models.BooleanField(default=False),
        ),
    ]
