# Generated by Django 3.1.5 on 2021-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0010_settings_acceptorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayName', models.CharField(max_length=100, null=True)),
                ('live_key_secret', models.CharField(max_length=100, null=True)),
                ('live_merchant_Key', models.CharField(max_length=100, null=True)),
                ('test_key_secret', models.CharField(max_length=100, null=True)),
                ('test_merchant_Key', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
