# Generated by Django 3.1.5 on 2021-05-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_paymentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiprocketToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
