# Generated by Django 3.1.5 on 2021-05-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_shiprockettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking_id',
            field=models.IntegerField(default=0),
        ),
    ]
