# Generated by Django 3.1.1 on 2020-09-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0004_subsubcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(max_length=50)),
                ('skuCode', models.CharField(max_length=50)),
                ('productName', models.CharField(blank=True, max_length=2000, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('mrp', models.IntegerField(default=1)),
                ('sellingPrice', models.IntegerField(default=1)),
                ('totalReview', models.IntegerField(default=0)),
                ('avgReview', models.DecimalField(decimal_places=1, max_digits=2)),
                ('viewCount', models.IntegerField(default=0)),
                ('vendorActiveStatus', models.BooleanField(default=True)),
                ('adminActiveStatus', models.BooleanField(default=True)),
                ('totalStock', models.IntegerField(default=0)),
                ('availableStock', models.IntegerField(default=0)),
                ('cat_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('productBrandID',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productbrand')),
                ('productGroupID',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup')),
                ('sub_cat_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('sub_sub_cat_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subsubcategory')),
                (
                'user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='uploads/productImage/')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
