# Generated by Django 3.1.1 on 2020-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_auto_20200912_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avgReview',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
