# Generated by Django 3.1.1 on 2020-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200912_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contryOfOrigin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orderCount',
            field=models.IntegerField(default=0),
        ),
    ]
