# Generated by Django 3.1.5 on 2021-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201019_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
