# Generated by Django 3.1.5 on 2021-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210429_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
