# Generated by Django 3.1.5 on 2021-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210430_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
    ]
