# Generated by Django 3.1.5 on 2021-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210430_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productBrandID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productGroupID',
            field=models.IntegerField(default=0),
        ),
    ]
