# Generated by Django 3.1.5 on 2021-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210507_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productBrandID',
            new_name='productBrandID_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productGroupID',
            new_name='productGroupID_id',
        ),
    ]
