# Generated by Django 3.1.14 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210507_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wihoutgstprice',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_sub_cat_id',
            field=models.IntegerField(default=1),
        ),
    ]
