# Generated by Django 3.1.5 on 2021-02-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerads',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='videoads',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
