# Generated by Django 3.1.5 on 2021-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210217_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerads',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoads',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
