# Generated by Django 3.1.5 on 2021-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20210217_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerads',
            name='views',
        ),
        migrations.AddField(
            model_name='bannerads',
            name='endingDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='payableAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='startingDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='totalDays',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='bannerads',
            name='transID',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='videoads',
            name='payableAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoads',
            name='transID',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
