# Generated by Django 3.1.5 on 2021-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210217_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerads',
            name='totalDays',
            field=models.IntegerField(default=0),
        ),
    ]
