# Generated by Django 3.1.5 on 2021-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20210217_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerads',
            name='planID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoads',
            name='planID',
            field=models.IntegerField(default=0),
        ),
    ]
