# Generated by Django 3.1.5 on 2021-02-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20210218_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('planPrice', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAdsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('planPrice', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
