# Generated by Django 3.1.5 on 2021-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_banneradsplan_videoadsplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneradsplan',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='videoadsplan',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
