# Generated by Django 3.1.5 on 2021-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20210219_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadsplan',
            name='maxPlayTime',
            field=models.IntegerField(default=0),
        ),
    ]
