# Generated by Django 3.1.5 on 2021-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_videoadsplan_maxplaytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adsstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_id', models.ImageField(default=0, upload_to='')),
                ('play_date', models.DateField(auto_now=True)),
                ('ads_status', models.BooleanField(default=1)),
            ],
        ),
    ]
