# Generated by Django 3.1.5 on 2021-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20210225_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default=0, max_length=100)),
                ('companyLogo', models.ImageField(null=True, upload_to='uploads/ads/companyLogo/')),
                ('companyShortDescriptions', models.TextField(default=0, max_length=5000)),
                ('domainName', models.CharField(default=0, max_length=500)),
                ('redirectURL', models.CharField(default=0, max_length=500)),
                ('video', models.FileField(null=True, upload_to='uploads/ads/video/')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Adsstatus',
        ),
        migrations.DeleteModel(
            name='BannerAds',
        ),
        migrations.DeleteModel(
            name='BannerAdsPlan',
        ),
        migrations.DeleteModel(
            name='VideoAds',
        ),
        migrations.DeleteModel(
            name='VideoAdsPlan',
        ),
    ]
