# Generated by Django 3.1.5 on 2021-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_video_videocategory_videokeyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='uploads/powerVideo/thumbnail'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='uploads/powerVideo/video'),
        ),
    ]
