# Generated by Django 3.1.1 on 2020-09-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharNumber', models.CharField(max_length=50)),
                ('panNumber', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=200)),
                ('companyLogo', models.ImageField(upload_to='uploads/companyLogo/')),
                ('gstNumber', models.CharField(max_length=200)),
                ('aadharImage', models.ImageField(upload_to='uploads/aadharImage/')),
                ('panImage', models.ImageField(upload_to='uploads/panImage/')),
                ('vendorSign', models.ImageField(upload_to='uploads/vendorSign/')),
                ('vendorApproveStatus', models.BooleanField(default=False)),
                ('ProfileUpdatePermission', models.BooleanField(default=True)),
                ('POS', models.BooleanField(default=False)),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeStatus', models.BooleanField(default=False)),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDetails.vendordetails')),
            ],
        ),
    ]
