# Generated by Django 3.1.5 on 2021-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0008_subscriptionplanpurchase_videostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewordPointForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
