# Generated by Django 3.1.5 on 2021-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetails', '0009_rewordpointforuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumOrderValueForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
