# Generated by Django 3.1.1 on 2020-09-10 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_icon',
        ),
    ]
