# Generated by Django 3.1.1 on 2020-09-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0002_auto_20200910_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=20)),
                ('sub_cat_icon', models.ImageField(upload_to='uploads/subcategory/')),
                ('commission', models.IntegerField(default=1)),
                ('gst', models.IntegerField(default=1)),
                ('homepage_view_status', models.BooleanField(default=False)),
                ('cat_id',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
