# Generated by Django 3.1.5 on 2021-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_cat_icon',
            field=models.ImageField(null=True, upload_to='uploads/subcategory/'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='sub_sub_cat_icon',
            field=models.ImageField(null=True, upload_to='uploads/subsubcategory/'),
        ),
    ]
