# Generated by Django 3.1.1 on 2020-10-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201007_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingPaymentID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='booking.bookingpayment'),
            preserve_default=False,
        ),
    ]
