# Generated by Django 3.1.1 on 2020-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_bookingpaymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='returnStatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
