# Generated by Django 3.1.1 on 2020-10-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_returnstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='returnStatus',
        ),
    ]
