# Generated by Django 3.1.1 on 2020-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_returnstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='returnExpairStatus',
            field=models.BooleanField(default=False),
        ),
    ]
