# Generated by Django 3.1.5 on 2021-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_returnexpairstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='walletPoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='walletPoint',
            field=models.IntegerField(default=0),
        ),
    ]
