# Generated by Django 3.1.5 on 2021-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210410_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deliveryBoyId',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='returnBoyId',
        ),
        migrations.AddField(
            model_name='booking',
            name='deliveryBoyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='deliveryBoyPhone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='returnBoyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='returnBoyPhone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
