# Generated by Django 3.1.5 on 2021-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210505_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoiceNumber',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='outForDeliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='outForPicupDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderID',
            field=models.CharField(max_length=120),
        ),
    ]
