# Generated by Django 3.1.5 on 2021-05-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210506_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='productGST',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='productSellingPrice',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
    ]
