# Generated by Django 3.1.14 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210507_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor_paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
