# Generated by Django 3.1.5 on 2021-03-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referUserID',
            field=models.IntegerField(default=0),
        ),
    ]
