# Generated by Django 3.1.5 on 2021-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_referuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptionPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
