# Generated by Django 3.1.2 on 2020-10-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201019_1052'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandTotal', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='POSBookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('productSellingPrice', models.IntegerField(default=0)),
                ('productTotalPrice', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=False)),
                ('POSBookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.posbooking')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
