# Generated by Django 3.1.2 on 2020-10-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posbooking_posbookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='posbooking',
            name='orderID',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
