# Generated by Django 3.1.2 on 2020-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_posbooking_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posbooking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
