# Generated by Django 3.1.2 on 2020-10-30 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0004_posbooking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posbooking',
            name='posID',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
    ]
