# Generated by Django 3.1.1 on 2020-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walletwithdraw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
