# Generated by Django 3.1.5 on 2021-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210409_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='totalPoint',
            field=models.IntegerField(default=0),
        ),
    ]
