# Generated by Django 3.1.1 on 2020-09-12 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(max_length=6)),
                ('minPrice', models.IntegerField(default=0)),
                ('deliveryCharge', models.IntegerField(default=0)),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(max_length=6)),
                ('activeStatus', models.BooleanField(default=True)),
                (
                'user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
