# Generated by Django 3.1.1 on 2020-09-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0002_deliveryboypincode_deliverypincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypincode',
            name='pincode',
            field=models.IntegerField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='optionalPhone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
