# Generated by Django 3.1.1 on 2020-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0003_auto_20200912_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='deliveryboypincode',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='deliverypincode',
            name='pincode',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
