# Generated by Django 3.1.1 on 2020-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200913_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
