# Generated by Django 3.1.1 on 2020-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20201007_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(default='na', max_length=150, null=True),
        ),
    ]
