# Generated by Django 3.1.1 on 2020-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20201007_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='optionalPhone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
