# Generated by Django 3.1.5 on 2021-01-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20201007_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypincode',
            name='cod',
            field=models.CharField(default='YES', max_length=100),
        ),
    ]
