# Generated by Django 3.1.1 on 2020-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaybanner',
            name='image',
            field=models.ImageField(upload_to='uploads/displayBanner/'),
        ),
    ]
