# Generated by Django 3.1.1 on 2020-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20200912_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='couponValidDate',
            field=models.DateField(null=True),
        ),
    ]
